- name: "Include pkg configuration"
  ansible.builtin.import_tasks: pkg.yml

- name: "Update db and install required RHVoice packages"
  ansible.builtin.command:
    cmd: pacman -Sy --needed --noconfirm --noprogressbar {{ pkgs }}
  changed_when: false
